data:
  root: "./data/cam0_controller_20260316/mav0/cam0/data"
  img_width: 2560
  img_height: 481
  total_cameras_number: 4
  selected_cameras: [0] # choose any sequential cameras, max list is [0, 1, 2, 3]


controllers:
  right_controller:
    config_path: "./data/controller_A85K6081930636R.json"

blob_detection:
  min_threshold: 10
  min_area: 2
  max_area: 50
