#!/usr/bin/env python3
"""Resumable (ablation x recording) job runner for the thesis's final evaluation.

Runs the tracker (main.py of a code SNAPSHOT, never the live tree) once per job with a config
generated by ablations.py, adapted per job (data root, output paths, frame range, logging).
Output layout: <out>/<ablation>/<recording>/{config.yml,pose.csv,vision_pose.csv,mocap_gt/,run.log,DONE.json}

Examples:
  make_snapshot.sh /tmp/snap HEAD
  python run_ablations.py --snapshot /tmp/snap --out /data/abl --ablations full,imu_off --recordings all --dry-run
  python run_ablations.py --snapshot /tmp/snap --out /data/abl --ablations all --recordings static_dark --frames 3000:3200 --warmup 100 --jobs 2
Resumable: jobs with DONE.json (returncode 0) are skipped unless --force. At most 3 concurrent jobs.
"""
import argparse
import ast
import hashlib
import json
import os
import platform
import re
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from ablations import ABLATIONS, NEEDS_CODE, generate_text  # noqa: E402
from yaml_patch import set_value  # noqa: E402

LIVE_REPO = Path(__file__).resolve().parents[3]
RECORDINGS_ROOT = Path("/home/nikitakarpuks/Downloads/recordings-aug26")
QUIET_LOG_KEYS = ["log_matching_decisions", "log_batch_orchestration", "log_pose_fusion", "log_occlusion",
                  "log_proximity_match", "log_best", "log_blob_detection"]
_COUNT_MISMATCH_RE = re.compile(
    r"data\.layout='per_camera_folders' requires the same image count in every "
    r"camera folder, got (\{.*\})")


def rec_short(rec_dir):
    parts = rec_dir.name.split("_", 3)
    return parts[3] if len(parts) == 4 else rec_dir.name


def discover_recordings(names):
    recs = sorted(p for p in RECORDINGS_ROOT.iterdir() if p.is_dir() and p.name.startswith("euroc_recording_"))
    by_name = {rec_short(p): p for p in recs}
    if names == "all":
        return by_name
    missing = [n for n in names.split(",") if n not in by_name]
    if missing:
        raise SystemExit(f"unknown recordings {missing}; have {sorted(by_name)}")
    return {n: by_name[n] for n in names.split(",")}


def absolutize_data_paths(text, data_root):
    """`key: "./data/..."` (uncommented lines only) -> absolute path into the live data tree, since
    calibration/bridge files are partly untracked and therefore absent from a git snapshot."""
    return re.sub(r'(?m)^(\s*[A-Za-z0-9_]+:\s*)"\./data/', lambda m: f'{m.group(1)}"{data_root}/data/', text)


def frame_stems(base_cfg, rec_dir):
    d = base_cfg["data"]
    idx = 0 + int(d.get("controller_cam_start_index", 0))
    folder = rec_dir / "mav0" / d["camera_folder_pattern"].format(idx=idx) / d.get("images_subdir", "")
    return sorted(int(p.stem) for p in folder.glob("*.png"))


def build_job_config(base_text, ablation, rec_dir, job_dir, run_lo, run_hi, workers, viz, data_root, sequential=False):
    txt = generate_text(base_text, ablation)
    txt = absolutize_data_paths(txt, data_root)
    txt_holder = [txt]

    def put(path, v):
        txt_holder[0] = set_value(txt_holder[0], path, v)

    put(["data", "root"], str(rec_dir / "mav0"))
    put(["data", "frame_range", "lower"], run_lo)
    put(["data", "frame_range", "upper"], run_hi)
    put(["debug", "calibration_csv"], None)
    put(["debug", "pose_csv"], str(job_dir / "pose.csv"))
    put(["debug", "vision_pose_csv"], str(job_dir / "vision_pose.csv"))
    put(["debug", "led_detections_csv"], None)
    put(["debug", "mocap_log_dir"], str(job_dir / "mocap_gt"))
    put(["visualization", "save_recording"], None)
    put(["visualization", "visualize_save"], False)
    put(["visualization", "visualize_rerun"], False)
    put(["visualization", "pose_fusion_debug", "enabled"], False)
    put(["visualization", "enabled"], bool(viz))
    for k in QUIET_LOG_KEYS:
        try:
            put(["debug", k], False)
        except KeyError:
            print(f"  warn: debug.{k} not in config", file=sys.stderr)
    if workers:
        put(["matching", "parallel_search_workers"], int(workers))
    if sequential:
        put(["matching", "parallel_search_enabled"], False)
    return txt_holder[0]


def provenance(snapshot, out, cfg):
    p = out / "PROVENANCE.json"
    if p.exists():
        return
    files = {}
    for path in [cfg["cameras"]["intrinsics_path"], cfg["cameras"].get("mocap_calib_path")] + \
                [c.get(k) for c in cfg["controllers"].values() for k in ("config_path", "mocap_bridge_path", "mocap_calib_path")]:
        if path:
            f = Path(path)
            f = f if f.is_absolute() else LIVE_REPO / path
            if f.exists():
                files[str(f)] = hashlib.sha256(f.read_bytes()).hexdigest()
    commit = (Path(snapshot) / "COMMIT").read_text().strip() if (Path(snapshot) / "COMMIT").exists() else "unknown"
    out.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps({"commit": commit, "created": time.strftime("%F %T"), "host": platform.node(),
                             "nproc": os.cpu_count(), "python": sys.version.split()[0], "input_file_sha256": files},
                            indent=2))


def run_job(job, snapshot, python, nice, dry):
    job_dir = job["dir"]
    done = job_dir / "DONE.json"
    label = f"[{job['ablation']}/{job['rec']}]"
    if dry:
        print(f"{label} would run frames {job['run_lo']}:{job['run_hi']} eval_from_ts={job['eval_from_ts']} -> {job_dir}")
        return {"label": label, "status": "dry"}
    job_dir.mkdir(parents=True, exist_ok=True)
    cfg_path, log_path = job_dir / "config.yml", job_dir / "run.log"
    cfg_path.write_text(job["cfg_text"])
    env = dict(os.environ, OMP_NUM_THREADS="1", OPENBLAS_NUM_THREADS="1", MKL_NUM_THREADS="1")
    cmd = (["nice", "-n", str(nice)] if nice else []) + [python, "main.py", str(cfg_path)]

    def _run():
        with open(log_path, "w") as lf:
            return subprocess.run(cmd, cwd=str(snapshot), stdout=lf, stderr=subprocess.STDOUT, env=env).returncode

    t0 = time.time()
    print(f"{label} start", flush=True)
    rc = _run()
    if rc != 0:
        m = _COUNT_MISMATCH_RE.search(log_path.read_text())
        if m:  # one camera folder is shorter by a frame or two: trim to the common count and retry once
            counts = ast.literal_eval(m.group(1))
            mn = min(counts.values())
            print(f"{label} per-camera count mismatch {counts}: retry with upper={mn}", flush=True)
            job["cfg_text"] = set_value(job["cfg_text"], ["data", "frame_range", "upper"], mn)
            cfg_path.write_text(job["cfg_text"])
            t0 = time.time()
            rc = _run()
    el = time.time() - t0
    done.write_text(json.dumps({"returncode": rc, "elapsed_s": el, "run_lo": job["run_lo"], "run_hi": job["run_hi"],
                                "eval_from_ts": job["eval_from_ts"], "eval_to_ts": job["eval_to_ts"],
                                "ablation": job["ablation"], "recording": job["rec"]}, indent=1))
    print(f"{label} {'OK' if rc == 0 else 'FAILED rc=%d' % rc} in {el:.0f}s", flush=True)
    return {"label": label, "status": "ok" if rc == 0 else "failed"}


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--snapshot", required=True, help="code snapshot dir (make_snapshot.sh)")
    ap.add_argument("--out", required=True)
    ap.add_argument("--ablations", default="full")
    ap.add_argument("--recordings", default="all")
    ap.add_argument("--frames", default=None, help="LO:HI subsequence to EVALUATE (frame indices, HI exclusive)")
    ap.add_argument("--warmup", type=int, default=0, help="extra frames before LO that are run but excluded from metrics")
    ap.add_argument("--jobs", type=int, default=1, help="concurrent jobs (<=3)")
    ap.add_argument("--workers", type=int, default=None,
                    help="matching.parallel_search_workers override (default: config value if --jobs 1, else 6//jobs)")
    ap.add_argument("--sequential", action="store_true", help="matching.parallel_search_enabled=false (no process pool)")
    ap.add_argument("--viz", choices=["off", "on"], default="off")
    ap.add_argument("--nice", type=int, default=10)
    ap.add_argument("--python", default=sys.executable)
    ap.add_argument("--data-root", default=str(LIVE_REPO), help="repo whose ./data/ holds untracked calibration/bridge files")
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()
    if not 1 <= a.jobs <= 3:
        raise SystemExit("--jobs must be 1..3 (shared machine)")
    snapshot, out = Path(a.snapshot), Path(a.out)
    base_text = (snapshot / "config" / "config.yml").read_text()
    base_cfg = yaml.safe_load(base_text)
    names = list(ABLATIONS) if a.ablations == "all" else a.ablations.split(",")
    for n in names:
        if n in NEEDS_CODE:
            raise SystemExit(f"'{n}' needs a code change: {NEEDS_CODE[n][1]}")
        if n not in ABLATIONS:
            raise SystemExit(f"unknown ablation '{n}'; see `python ablations.py list`")
    recs = discover_recordings(a.recordings)
    workers = a.workers if a.workers else (None if a.jobs == 1 else max(1, 6 // a.jobs))
    lo = hi = None
    if a.frames:
        lo, hi = (int(x) for x in a.frames.split(":"))
    jobs = []
    for n in names:
        for short, rec_dir in recs.items():
            stems = frame_stems(base_cfg, rec_dir) if a.frames else None
            run_lo = max(0, lo - a.warmup) if a.frames else None
            run_hi = hi if a.frames else None
            jd = out / n / short
            jobs.append({"ablation": n, "rec": short, "dir": jd, "run_lo": run_lo, "run_hi": run_hi,
                         "eval_from_ts": stems[lo] if stems else None,
                         "eval_to_ts": stems[min(hi, len(stems)) - 1] if stems else None,
                         "cfg_text": build_job_config(base_text, n, rec_dir, jd, run_lo, run_hi, workers,
                                                      a.viz == "on", a.data_root, a.sequential)})
    todo = []
    for j in jobs:
        d = j["dir"] / "DONE.json"
        if d.exists() and not a.force and json.loads(d.read_text()).get("returncode") == 0:
            print(f"[{j['ablation']}/{j['rec']}] done, skipping")
        else:
            todo.append(j)
    print(f"{len(jobs)} jobs, {len(todo)} to run, {a.jobs} concurrent, workers/job={workers or 'config'}")
    if a.dry_run and jobs:
        from yaml_patch import diff_keys
        print("keys changed vs the snapshot config for the first job:",
              sorted("/".join(k) for k in diff_keys(base_text, jobs[0]["cfg_text"])))
    if not a.dry_run:
        provenance(snapshot, out, base_cfg)
    with ThreadPoolExecutor(max_workers=a.jobs) as ex:
        res = list(ex.map(lambda j: run_job(j, snapshot, a.python, a.nice, a.dry_run), todo))
    bad = [r["label"] for r in res if r["status"] == "failed"]
    print("failed:", bad or "none")
    sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
